#!/bin/bash

exec 2>&1
exec {{pkgPathFor "core/jre8"}}/bin/java -jar {{cfg.java_opts}} {{pkg.path}}/sample-springboot-app-{{pkg.version}}.jar --spring.config.location={{pkg.svc_config_path}}/application.properties
